<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div>
        <label><?php echo $this->__('Legal Form') ?>*</label>
        <span>
      <select  title="<?php echo $this->__('Legal Form') ?>" name="payment[billie_legal_form]">
          <option value="90101"><?php echo $this->__('AG & Co. KG') ?></option>
          <option value="11001"><?php echo $this->__('Aktiengesellschaft') ?></option>
          <option value="19022"><?php echo $this->__('Anstalt') ?></option>
      </select>
    </span>
    </div>
    <div>
        <label><?php echo $this->__('Industry Sector') ?>*</label>
        <span>
      <input type="text" title="<?php echo $this->__('Industry Sector') ?>" name="payment[billie_industry_sector]" value="<?php echo $this->htmlEscape($this->getInfoData('billie_industry_sector')) ?>" />
    </span>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>