<?php
//print_r($this->helper('billie_core')->getLegalForms());
?>
<div class="form-list" id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none;">
    <div>
        <label><?php echo $this->__('Legal Form') ?>*</label>
        <span>
      <select  title="<?php echo $this->__('Legal Form') ?>" name="payment[billie_legal_form]">
          <option value=""><?php echo $this->__('please select') ?></option>
          <?php foreach ($this->helper('billie_core')->getAllLegalForms() as $legalForm):?>
          <option value="<?php echo $legalForm['code'] ?>"><?php echo $legalForm['label'] ?></option>
          <?php endforeach; ?>
      </select>
    </span>
    </div>
    <div>
        <label><?php echo $this->__('Industry Sector') ?>*</label>
        <span>
      <input type="text" title="<?php echo $this->__('Industry Sector') ?>" name="payment[billie_industry_sector]" value="<?php echo $this->htmlEscape($this->getInfoData('billie_industry_sector')) ?>" />
    </span>
    </div>
</div>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>